<a href="https://colab.research.google.com/github/pradeepthigunturi-creator/c_programming-language/blob/main/pyhton%20numpy%20functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#array with zeros

In [ ]:
a=np.array([2,3,4,5])



In [ ]:
print(np.zeros((4,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#array with ones
print(np.ones(4))

[1. 1. 1. 1.]


In [ ]:
print(np.ones((4,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#random function
import random
import numpy as np
print(np.random.rand(1,10))
print(np.random.rand(5,2))
print(np.random.randint(5))#selects a random number btw 0 to 5
print(np.random.randint(1,10,5))#(start,end,how many random number req)
print (np.array([[1,3,2],[4,5,6,],[8,9,7]]))

[[0.2087967  0.87601593 0.02128132 0.1535623  0.93879614 0.18019921
  0.78716456 0.50017038 0.90269676 0.97800959]]
[[0.66305524 0.35412235]
 [0.82739175 0.26683403]
 [0.34605497 0.39941008]
 [0.80250103 0.42918018]
 [0.45439098 0.66687235]]
4
[4 8 2 9 9]
[[1 3 2]
 [4 5 6]
 [8 9 7]]


In [ ]:
import random
import numpy as np

print(np.random.rand(3,3))
print(np.random.randint(5,10)) # Fixed: Changed high value to be greater than low
print(np.random.randint(1,10,5))#in the range od 1 to 10 i need 5 elements


[[0.59479789 0.00105628 0.77604777]
 [0.49417823 0.66383896 0.34548313]
 [0.37955694 0.34211223 0.37068939]]
5
[9 4 8 6 3]
[0 1 2 3 4]
[1 4 7]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.    3.25  5.5   7.75 10.  ]
